### ISSUE TITLE
Slots-specific spells disappear when sorting magic inventory

### ISSUE THREAD

**Issue by DiscoCokkroach** [sleepeybunney/maelstrom#27]
I had it happen with Rapture and Full-cure in my particular instance, but I can only assume that this happens with the other ones, as well.

I don't know if it works the same way with Percent and other cut content-spells, but I would assume it does.

You can still sort your magic inventory manually and keep a given Slots spell or give it to another party member.

**Comment by DiscoCokkroach** [comment]
I need to update my Maelstrom to see if this is still an issue in the current release.

**Comment by DiscoCokkroach** [comment]
This happened to me on v0.3.2, but I rerolled with v0.4 and it still happens.

**Comment by sleepeybunney** [comment]
I've added the extra spells to the sorting file so they don't get rearranged out of existence (2cbfc26)

Thanks for the report, I wouldn't have thought to check that!

**Comment by Spoutboy** [comment]
Hi there, just wanted to let you know that with Version 0.5 the issue reoccures.
Maybe the fix got removed in v0.5? Or something else happened?

The Spells vanished after rearranging the Magic via the Menu.
