### ISSUE TITLE
Infinite load when pressing GO

### ISSUE THREAD

**Issue by MarcBedard** [sleepeybunney/maelstrom#30]
I can't seem to be able to patch my clean version of FF8:Remaster on PC Steam. I gave it a good 30 minutes on a SSD drive. I can see the loading icon at the bottom right and the seed was generated.

The data file are created (original and .bak). It just simply never seems to 'end'. I tried launching the game and the randomizer isn't applied.  Also, I know it ain't ever finished because the 'spoiler' file is never created.
![ff8_maelstrom](https://user-images.githubusercontent.com/22872446/100291574-26ce3400-2f4c-11eb-983d-4dedcce7ba4f.png)

**Comment by sleepeybunney** [comment]
Sorry about this, I'll look into it. Could you show me what's in the lang-en folder?

**Comment by MarcBedard** [comment]
No fuss about it :) Thank you so much for actually replying to me. Here's the content of the Data/lang-en folder.
![ff8_maelstrom_lang_en](https://user-images.githubusercontent.com/22872446/100449229-8da13980-3081-11eb-977b-146018b022db.png)

**Comment by MarcBedard** [comment]
Hello Sleepey, I wanted to update this. I was able to run the program after running it in compatibility mode for windows 7 and as administrator after a fresh restart of my PC. Perhaps one of those was blocking it. This can be closed :)
