### ISSUE TITLE
Slots-specific spells disappear when sorting magic inventory (again) - Version 0.5

### ISSUE THREAD

**Issue by Spoutboy** [sleepeybunney/maelstrom#36]
Hi there, just wanted to let you know that with Version 0.5 this specific issue reoccures.
Maybe the fix got removed in v0.5? Or something else happened?

The spells disappear after rearranging magic via the Menu.

**Comment by sleepeybunney** [comment]
Looks like I forgot to apply the sorting fix when you use random enemy draws & not random draw points

**Comment by sleepeybunney** [comment]
Fixed in v0.5.1
