### ISSUE TITLE
HELP 

### ISSUE THREAD

**Issue by jake-pacolypse** [sleepeybunney/maelstrom#37]
Trying to run on windows 10 updated .net framework to most recent but once i unpack and try to get the maelstrom.exe to run i get a loading circle then  nothing. help would be appreciated.

**Comment by sleepeybunney** [comment]
Have you unpacked all the files? Not sure what else it could be. Can you post a screenshot?

**Comment by jake-pacolypse** [comment]
I believe they're all unpacked I've deleted and downloaded 3 times. 
![20210401_080913](https://user-images.githubusercontent.com/81597069/113292479-91103000-92c2-11eb-9d03-ac186546684c.jpg)

**Comment by triabolical** [comment]
If this isn't resolved yet, I had a similar issue where the program would crash with some of the settings. You might want to take a look. 

https://github.com/sleepeybunney/maelstrom/issues/47

**Comment by sleepeybunney** [comment]
It won't run from that 7zip screen - after you Extract you should close that window & go find the folder it extracted to with the normal Windows file explorer

**Comment by jake-pacolypse** [comment]
Thank you i finally got it to work.
