### ISSUE TITLE
Tonberry King replacement is immortal

### ISSUE THREAD

**Issue by JayH2971** [sleepeybunney/maelstrom#61]
Maelstrom 0.5.3
Seed 361767223

I beat enough Tonberries to make the replacement boss appear, a Propagator. However, I kept fighting it for over 10 minutes and it didn't die. My next attempt, I threw a Hi-Potion at it on the assumption that it spawned with zero HP, and then scanned it (should have done that in reverse order, but that's how it went). This is the result:

![image](https://user-images.githubusercontent.com/37541932/142979393-66198e36-32d5-461f-8dce-522e641c6426.png)

I then hit it more, and it didn't die. This is the next scan:

![image](https://user-images.githubusercontent.com/37541932/142979818-75006125-5b80-4e9d-9423-e84d4bc23af3.png)

The boss will not die.

**Comment by sleepeybunney** [comment]
Thanks for reporting this!

Maelstrom created a new death script for Propagator here, but I forgot to include the part where it actually dies.

Fixed in 8f8ad3b and 1d40e4d
